{"uuid": "1e2c31a1-4ee0-4f19-a069-5afffe8ebb5d", "children": ["820e1d2b-5597-4476-a80e-dfeaf6603850"], "befores": [{"name": "create_order", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 96, in create_order\n    token = create_user[1].json()[\"accessToken\"]  # Получение токена пользователя\n            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "start": 1739853449571, "stop": 1739853449571}], "start": 1739853449571, "stop": 1739853449718}