{"name": "Проверка появления номера созданного заказа в разделе \"В работе\"", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=57680): Read timed out. (read timeout=120)", "trace": "self = <urllib3.connectionpool.HTTPConnectionPool object at 0x0000011C1803EB50>, conn = <urllib3.connection.HTTPConnection object at 0x0000011C1812F790>, method = 'POST'\nurl = '/session/f9d11903980a8b34e20c1658ca1d04dc/url', body = '{\"url\": \"https://stellarburgers.nomoreparties.site\"}'\nheaders = HTTPHeaderDict({'Accept': 'application/json', 'Content-Type': 'application/json;charset=UTF-8', 'User-Agent': 'selenium/4.27.1 (python windows)', 'Connection': 'keep-alive'})\nretries = Retry(total=3, connect=None, read=None, redirect=None, status=None), timeout = Timeout(connect=120, read=120, total=None), chunked = False, response_conn = None, preload_content = True\ndecode_content = True, enforce_content_length = True\n\n    def _make_request(\n        self,\n        conn: BaseHTTPConnection,\n        method: str,\n        url: str,\n        body: _TYPE_BODY | None = None,\n        headers: typing.Mapping[str, str] | None = None,\n        retries: Retry | None = None,\n        timeout: _TYPE_TIMEOUT = _DEFAULT_TIMEOUT,\n        chunked: bool = False,\n        response_conn: BaseHTTPConnection | None = None,\n        preload_content: bool = True,\n        decode_content: bool = True,\n        enforce_content_length: bool = True,\n    ) -> BaseHTTPResponse:\n        \"\"\"\n        Perform a request on a given urllib connection object taken from our\n        pool.\n    \n        :param conn:\n            a connection from one of our connection pools\n    \n        :param method:\n            HTTP request method (such as GET, POST, PUT, etc.)\n    \n        :param url:\n            The URL to perform the request on.\n    \n        :param body:\n            Data to send in the request body, either :class:`str`, :class:`bytes`,\n            an iterable of :class:`str`/:class:`bytes`, or a file-like object.\n    \n        :param headers:\n            Dictionary of custom headers to send, such as User-Agent,\n            If-None-Match, etc. If None, pool headers are used. If provided,\n            these headers completely replace any pool-specific headers.\n    \n        :param retries:\n            Configure the number of retries to allow before raising a\n            :class:`~urllib3.exceptions.MaxRetryError` exception.\n    \n            Pass ``None`` to retry until you receive a response. Pass a\n            :class:`~urllib3.util.retry.Retry` object for fine-grained control\n            over different types of retries.\n            Pass an integer number to retry connection errors that many times,\n            but no other types of errors. Pass zero to never retry.\n    \n            If ``False``, then retries are disabled and any exception is raised\n            immediately. Also, instead of raising a MaxRetryError on redirects,\n            the redirect response will be returned.\n    \n        :type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.\n    \n        :param timeout:\n            If specified, overrides the default timeout for this one\n            request. It may be a float (in seconds) or an instance of\n            :class:`urllib3.util.Timeout`.\n    \n        :param chunked:\n            If True, urllib3 will send the body using chunked transfer\n            encoding. Otherwise, urllib3 will send the body using the standard\n            content-length form. Defaults to False.\n    \n        :param response_conn:\n            Set this to ``None`` if you will handle releasing the connection or\n            set the connection to have the response release it.\n    \n        :param preload_content:\n          If True, the response's body will be preloaded during construction.\n    \n        :param decode_content:\n            If True, will attempt to decode the body based on the\n            'content-encoding' header.\n    \n        :param enforce_content_length:\n            Enforce content length checking. Body returned by server must match\n            value of Content-Length header, if present. Otherwise, raise error.\n        \"\"\"\n        self.num_requests += 1\n    \n        timeout_obj = self._get_timeout(timeout)\n        timeout_obj.start_connect()\n        conn.timeout = Timeout.resolve_default_timeout(timeout_obj.connect_timeout)\n    \n        try:\n            # Trigger any extra validation we need to do.\n            try:\n                self._validate_conn(conn)\n            except (SocketTimeout, BaseSSLError) as e:\n                self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)\n                raise\n    \n        # _validate_conn() starts the connection to an HTTPS proxy\n        # so we need to wrap errors with 'ProxyError' here too.\n        except (\n            OSError,\n            NewConnectionError,\n            TimeoutError,\n            BaseSSLError,\n            CertificateError,\n            SSLError,\n        ) as e:\n            new_e: Exception = e\n            if isinstance(e, (BaseSSLError, CertificateError)):\n                new_e = SSLError(e)\n            # If the connection didn't successfully connect to it's proxy\n            # then there\n            if isinstance(\n                new_e, (OSError, NewConnectionError, TimeoutError, SSLError)\n            ) and (conn and conn.proxy and not conn.has_connected_to_proxy):\n                new_e = _wrap_proxy_error(new_e, conn.proxy.scheme)\n            raise new_e\n    \n        # conn.request() calls http.client.*.request, not the method in\n        # urllib3.request. It also calls makefile (recv) on the socket.\n        try:\n            conn.request(\n                method,\n                url,\n                body=body,\n                headers=headers,\n                chunked=chunked,\n                preload_content=preload_content,\n                decode_content=decode_content,\n                enforce_content_length=enforce_content_length,\n            )\n    \n        # We are swallowing BrokenPipeError (errno.EPIPE) since the server is\n        # legitimately able to close the connection after sending a valid response.\n        # With this behaviour, the received response is still readable.\n        except BrokenPipeError:\n            pass\n        except OSError as e:\n            # MacOS/Linux\n            # EPROTOTYPE and ECONNRESET are needed on macOS\n            # https://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/\n            # Condition changed later to emit ECONNRESET instead of only EPROTOTYPE.\n            if e.errno != errno.EPROTOTYPE and e.errno != errno.ECONNRESET:\n                raise\n    \n        # Reset the timeout for the recv() on the socket\n        read_timeout = timeout_obj.read_timeout\n    \n        if not conn.is_closed:\n            # In Python 3 socket.py will catch EAGAIN and return None when you\n            # try and read into the file pointer created by http.client, which\n            # instead raises a BadStatusLine exception. Instead of catching\n            # the exception and assuming all BadStatusLine exceptions are read\n            # timeouts, check for a zero timeout before making the request.\n            if read_timeout == 0:\n                raise ReadTimeoutError(\n                    self, url, f\"Read timed out. (read timeout={read_timeout})\"\n                )\n            conn.timeout = read_timeout\n    \n        # Receive the response from the server\n        try:\n>           response = conn.getresponse()\n\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py:537: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connection.py:466: in getresponse\n    httplib_response = super().getresponse()\nC:\\Users\\Mozha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:1428: in getresponse\n    response.begin()\nC:\\Users\\Mozha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:331: in begin\n    version, status, reason = self._read_status()\nC:\\Users\\Mozha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\http\\client.py:292: in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <socket.SocketIO object at 0x0000011C18163130>, b = <memory at 0x0000011C1802F4C0>\n\n    def readinto(self, b):\n        \"\"\"Read up to len(b) bytes into the writable buffer *b* and return\n        the number of bytes read.  If the socket is non-blocking and no bytes\n        are available, None is returned.\n    \n        If *b* is non-empty, a 0 return value indicates that the connection\n        was shutdown at the other end.\n        \"\"\"\n        self._checkClosed()\n        self._checkReadable()\n        if self._timeout_occurred:\n            raise OSError(\"cannot read from timed out object\")\n        try:\n>           return self._sock.recv_into(b)\nE           TimeoutError: timed out\n\nC:\\Users\\Mozha\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\socket.py:719: TimeoutError\n\nThe above exception was the direct cause of the following exception:\n\nrequest = <SubRequest 'browser' for <Function test_order_number_appeared_in_work[chrome]>>\n\n    @pytest.fixture(params=[\"chrome\", \"firefox\"])\n    def browser(request):\n        \"\"\"\n        Фикстура для инициализации и завершения работы веб-драйвера.\n        Поддерживает запуск тестов на Chrome и Firefox.\n        Возвращает экземпляр драйвера для использования в тестах.\n        \"\"\"\n        browser = None\n        with allure.step(f\"Инициализация браузера: {request.param}\"):\n            if request.param == \"chrome\":\n                options = webdriver.ChromeOptions()\n                options.add_argument(\"--start-maximized\")\n                browser = webdriver.Chrome(\n                    service=ChromeService(ChromeDriverManager().install()),\n                    options=options\n                )\n            elif request.param == \"firefox\":\n                options = webdriver.FirefoxOptions()\n                options.add_argument(\"--start-maximized\")\n                browser = webdriver.Firefox(\n                    service=FirefoxService(GeckoDriverManager().install()),\n                    options=options\n                )\n        with allure.step(f\"Открытие URL: {BASE_URL}\"):\n>           browser.get(BASE_URL)\n\nconftest.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:393: in get\n    self.execute(Command.GET, {\"url\": url})\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:382: in execute\n    response = self.command_executor.execute(driver_command, params)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:404: in execute\n    return self._request(command_info[0], url, body=data)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:428: in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py:144: in request\n    return self.request_encode_body(\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\_request_methods.py:279: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\poolmanager.py:444: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py:847: in urlopen\n    retries = retries.increment(\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\retry.py:470: in increment\n    raise reraise(type(error), error, _stacktrace)\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\util\\util.py:39: in reraise\n    raise value\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py:793: in urlopen\n    response = self._make_request(\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py:539: in _make_request\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x0000011C1803EB50>, err = TimeoutError('timed out'), url = '/session/f9d11903980a8b34e20c1658ca1d04dc/url', timeout_value = 120\n\n    def _raise_timeout(\n        self,\n        err: BaseSSLError | OSError | SocketTimeout,\n        url: str,\n        timeout_value: _TYPE_TIMEOUT | None,\n    ) -> None:\n        \"\"\"Is the error actually a timeout? Will raise a ReadTimeout or pass\"\"\"\n    \n        if isinstance(err, SocketTimeout):\n>           raise ReadTimeoutError(\n                self, url, f\"Read timed out. (read timeout={timeout_value})\"\n            ) from err\nE           urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=57680): Read timed out. (read timeout=120)\n\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\urllib3\\connectionpool.py:370: ReadTimeoutError"}, "description": "Тест проверяет, что после оформления заказа его номер появляется в разделе В работе", "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1739895918114, "stop": 1739895918114, "uuid": "1fe0f212-461b-4070-bebc-6aa34ada8645", "historyId": "ad63ed80f20485313bc5b0438e791b9a", "testCaseId": "d7747efc423636778c3317a10b46dea4", "fullName": "tests.test_feed_page.TestFeedPage#test_order_number_appeared_in_work", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed_page"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "DESKTOP-1H286BJ"}, {"name": "thread", "value": "25132-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed_page"}]}