{"uuid": "cca3169e-fdff-40ca-8b1f-fb6287f49d13", "children": ["02b4c09e-a4b0-44c3-915e-9821d0a7a660"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 95.25.48.134. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Tue, 18 Feb 2025 04:46:55 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1739855991', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '278', 'X-GitHub-Request-Id': 'F8C5:349A28:3D6D3F2:3F5F99B:67B410BF'}\n\n", "trace": "  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 38, in browser\n    service=FirefoxService(GeckoDriverManager().install()),\n                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 110, in find_driver\n    key = self.__get_metadata_key(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 144, in __get_metadata_key\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n        url=self.latest_release_url,\n        headers=self.auth_header\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 36, in get\n    self.validate_response(resp)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 19, in validate_response\n    raise ValueError(\n    ...<3 lines>...\n    )\n"}, "steps": [{"name": "Инициализация браузера: firefox", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 95.25.48.134. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Tue, 18 Feb 2025 04:46:55 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1739855991', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '278', 'X-GitHub-Request-Id': 'F8C5:349A28:3D6D3F2:3F5F99B:67B410BF'}\n\n", "trace": "  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 38, in browser\n    service=FirefoxService(GeckoDriverManager().install()),\n                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 110, in find_driver\n    key = self.__get_metadata_key(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 144, in __get_metadata_key\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n        url=self.latest_release_url,\n        headers=self.auth_header\n    )\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 36, in get\n    self.validate_response(resp)\n    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 19, in validate_response\n    raise ValueError(\n    ...<3 lines>...\n    )\n"}, "start": 1739854014285, "stop": 1739854016370}], "start": 1739854014285, "stop": 1739854016415}], "start": 1739854014285, "stop": 1739854020584}